auto:            true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            年华的博客
url:              http://knewtime.com
feed:             /atom.xml
author:
    name:         年华的博客
description:      "Lu Jianhua\'s Blog"
author_info:      <a href="http://knewtime.com/about">年华</a>

copyright:
    - Thanks to <a href="http://beiyuu.com/about" title="BeiYuu" target="_blank">BeiYuu</a> &copy; 2013
